version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant
    container_name: local-rag-qdrant
    restart: always
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - ./data/qdrant:/qdrant/storage
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

